#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tezca.Resource", IsApplication=true)]

namespace Tezca
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060005
			public const int theme_devicedefault_background = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int theme_devicedefault_dialog_background = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int theme_devicedefault_light_noactionbar_fullscreen_background = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int theme_holo_light_noactionbar_fullscreen_background = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int theme_material_light_dialog_noactionbar_background = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int theme_material_light_voice_background = 2131099652;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_account_box_black_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_business_black_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_email_black_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_lock_black_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Normal_Button = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Normal_EditText = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ProgessBar_Circular = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int red_button = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Register_EditText = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Text_Button = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000e
			public const int Bname = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int ContButton = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int DescInput = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int DescText = 2131165190;
			
			// aapt resource value: 0x7f07000f
			public const int Email = 2131165199;
			
			// aapt resource value: 0x7f07000b
			public const int LoginButton = 2131165195;
			
			// aapt resource value: 0x7f070004
			public const int NameText = 2131165188;
			
			// aapt resource value: 0x7f070010
			public const int Pass1 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int Pass2 = 2131165201;
			
			// aapt resource value: 0x7f070001
			public const int PriceInput = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int PriceText = 2131165189;
			
			// aapt resource value: 0x7f07000c
			public const int RegisterButton = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int User = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int editText1 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int editText2 = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int imageView1 = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int nameInput = 2131165184;
			
			// aapt resource value: 0x7f070012
			public const int progressBar = 2131165202;
			
			// aapt resource value: 0x7f070003
			public const int saveButton = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Additem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int info = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Register = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Register = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int App_Background_Bold = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int App_Background_Light = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int Button_Normal = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int EditText_Light = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int EditText_Light_Register = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int Prueba = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int TextView_Light = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int Theme_Custom = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int button_text = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
