#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tezca.Resource", IsApplication=true)]

namespace Tezca
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.fab.Resource.Attribute.fab_colorDisabled = global::Tezca.Resource.Attribute.fab_colorDisabled;
			global::com.refractored.fab.Resource.Attribute.fab_colorNormal = global::Tezca.Resource.Attribute.fab_colorNormal;
			global::com.refractored.fab.Resource.Attribute.fab_colorPressed = global::Tezca.Resource.Attribute.fab_colorPressed;
			global::com.refractored.fab.Resource.Attribute.fab_colorRipple = global::Tezca.Resource.Attribute.fab_colorRipple;
			global::com.refractored.fab.Resource.Attribute.fab_shadow = global::Tezca.Resource.Attribute.fab_shadow;
			global::com.refractored.fab.Resource.Attribute.fab_size = global::Tezca.Resource.Attribute.fab_size;
			global::com.refractored.fab.Resource.Attribute.layoutManager = global::Tezca.Resource.Attribute.layoutManager;
			global::com.refractored.fab.Resource.Attribute.reverseLayout = global::Tezca.Resource.Attribute.reverseLayout;
			global::com.refractored.fab.Resource.Attribute.spanCount = global::Tezca.Resource.Attribute.spanCount;
			global::com.refractored.fab.Resource.Attribute.stackFromEnd = global::Tezca.Resource.Attribute.stackFromEnd;
			global::com.refractored.fab.Resource.Color.fab_material_blue_500 = global::Tezca.Resource.Color.fab_material_blue_500;
			global::com.refractored.fab.Resource.Dimension.fab_elevation_lollipop = global::Tezca.Resource.Dimension.fab_elevation_lollipop;
			global::com.refractored.fab.Resource.Dimension.fab_scroll_threshold = global::Tezca.Resource.Dimension.fab_scroll_threshold;
			global::com.refractored.fab.Resource.Dimension.fab_shadow_size = global::Tezca.Resource.Dimension.fab_shadow_size;
			global::com.refractored.fab.Resource.Dimension.fab_size_mini = global::Tezca.Resource.Dimension.fab_size_mini;
			global::com.refractored.fab.Resource.Dimension.fab_size_normal = global::Tezca.Resource.Dimension.fab_size_normal;
			global::com.refractored.fab.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::Tezca.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::com.refractored.fab.Resource.Drawable.fab_shadow = global::Tezca.Resource.Drawable.fab_shadow;
			global::com.refractored.fab.Resource.Drawable.fab_shadow_mini = global::Tezca.Resource.Drawable.fab_shadow_mini;
			global::com.refractored.fab.Resource.Id.item_touch_helper_previous_elevation = global::Tezca.Resource.Id.item_touch_helper_previous_elevation;
			global::com.refractored.fab.Resource.Id.mini = global::Tezca.Resource.Id.mini;
			global::com.refractored.fab.Resource.Id.normal = global::Tezca.Resource.Id.normal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton = global::Tezca.Resource.Styleable.FloatingActionButton;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::Tezca.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::Tezca.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::Tezca.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::Tezca.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::Tezca.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_size = global::Tezca.Resource.Styleable.FloatingActionButton_fab_size;
			global::com.refractored.fab.Resource.Styleable.RecyclerView = global::Tezca.Resource.Styleable.RecyclerView;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_android_orientation = global::Tezca.Resource.Styleable.RecyclerView_android_orientation;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_layoutManager = global::Tezca.Resource.Styleable.RecyclerView_layoutManager;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_reverseLayout = global::Tezca.Resource.Styleable.RecyclerView_reverseLayout;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_spanCount = global::Tezca.Resource.Styleable.RecyclerView_spanCount;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_stackFromEnd = global::Tezca.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int cardBackgroundColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cardCornerRadius = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cardElevation = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cardMaxElevation = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int cardPreventCornerOverlap = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int cardUseCompatPadding = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int contentPadding = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public const int contentPaddingBottom = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public const int contentPaddingLeft = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int contentPaddingRight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int contentPaddingTop = 2130771981;
			
			// aapt resource value: 0x7f010011
			public const int fab_colorDisabled = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int fab_colorNormal = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int fab_colorPressed = 2130771983;
			
			// aapt resource value: 0x7f010012
			public const int fab_colorRipple = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int fab_shadow = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int fab_size = 2130771988;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int cardview_dark_background = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int cardview_light_background = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int cardview_shadow_end_color = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int cardview_shadow_start_color = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int fab_material_blue_500 = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int theme_devicedefault_background = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int theme_devicedefault_dialog_background = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int theme_devicedefault_light_noactionbar_fullscreen_background = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int theme_holo_light_noactionbar_fullscreen_background = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int theme_material_light_dialog_noactionbar_background = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int theme_material_light_voice_background = 2131165193;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040001
			public const int cardview_compat_inset_shadow = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int cardview_default_elevation = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int cardview_default_radius = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int fab_elevation_lollipop = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int fab_scroll_threshold = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int fab_shadow_size = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int fab_size_mini = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int fab_size_normal = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fab_shadow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fab_shadow_mini = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_account_box_black_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_add_circle_black_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_business_black_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_email_black_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_lock_black_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Logo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Normal_Button = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Normal_EditText = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ProgessBar_Circular = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int red_button = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Register_EditText = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Text_Button = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050013
			public const int Bname = 2131034131;
			
			// aapt resource value: 0x7f05000a
			public const int ContButton = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int DescInput = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int DescText = 2131034121;
			
			// aapt resource value: 0x7f050014
			public const int Email = 2131034132;
			
			// aapt resource value: 0x7f05000e
			public const int LoginButton = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int LoginText = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int MyButton = 2131034129;
			
			// aapt resource value: 0x7f050007
			public const int NameText = 2131034119;
			
			// aapt resource value: 0x7f050015
			public const int Pass1 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int Pass2 = 2131034134;
			
			// aapt resource value: 0x7f05000d
			public const int PassText = 2131034125;
			
			// aapt resource value: 0x7f050004
			public const int PriceInput = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int PriceText = 2131034120;
			
			// aapt resource value: 0x7f05000f
			public const int RegisterButton = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int User = 2131034130;
			
			// aapt resource value: 0x7f05000b
			public const int imageView1 = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int mini = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int nameInput = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int normal = 2131034114;
			
			// aapt resource value: 0x7f050017
			public const int progressBar = 2131034135;
			
			// aapt resource value: 0x7f050006
			public const int saveButton = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int toolbar = 2131034128;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Additem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int info = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Products = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Register = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int ApplicationName = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Hello = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int Register = 2131230722;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060006
			public const int App_Background_Bold = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int App_Background_Light = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int Base_CardView = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int Button_Normal = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int CardView = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int CardView_Dark = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int CardView_Light = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int Card_Normal = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int EditText_Light = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int EditText_Light_Register = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int Prueba = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int TextView_Light = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int Theme_Custom = 2131099661;
			
			// aapt resource value: 0x7f060004
			public const int button_text = 2131099652;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] FloatingActionButton = new int[] {
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
